<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="display-4 text-center mb-3">Editar cuenta</h2>
		</div>
	</div>
	<div class="row">
        <div class="col-md-3"></div>
		<div class="col-md-6">
		<form action="<?php echo APP_URL."cuentas/editar"; ?>" method="POST" accept-charset="utf-8">
			<input type="hidden" name="id" value="<?php echo $this->cuenta["id"]; ?>">
			
			<div class="input-group mb-3">
				<div class="input-group-prepend">
					<span class="input-group-text">Clave</span>
				</div>
				<input type="text" name="clave" value="<?php echo $this->cuenta["clave"]; ?>" class="form-control">
			</div>

			<div class="input-group mb-3">
				<div class="input-group-prepend">
					<span class="input-group-text">Nombre</span>
				</div>
				<input type="text" name="name" value="<?php echo $this->cuenta["name"]; ?>" class="form-control">
			</div>
			
		</div>
		<div class="col-md-12">
			<div class="row justify-content-center">
				<div class="col-md-2"></div>
				<div class="col-md-4">
					<button type="submit" class="btn btn-success btn-block">Guardar cambios</button>
				</div>
				
				<div class="col-md-3">
				    <a href="<?php echo APP_URL. "cuentas/index"; ?>" class="btn btn-outline-primary mb-3">Regresar</a>
				</div>
			</div>
		</div>
	</form>
	</div>
</div>