<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="display-4 text-center">Lista de cuentas</h2>
			<a href="<?php echo APP_URL. "cuentas/agregar"; ?>" class="btn btn-outline-success mb-3">Agregar Cuenta</a>
            <a href="<?php echo APP_URL. "categorias/index"; ?>" class="btn btn-outline-primary mb-3">Ver categorias</a>
            <a href="<?php echo APP_URL. "transacciones/index"; ?>" class="btn btn-outline-primary mb-3">Ver transacciones</a>
			<table border="1" class="table table-striped table-dark table-responsive-lg">
				<tr>
					<th><center>ID</center></th>
					<th><center>Nombre</center></th>
					<th><center>Acción</center></th>
				</tr>
                    <?php foreach ($this->cuentas as $cuenta): ?>
				<tr>
					<td><center><?php echo $cuenta["accounts"]["id"]; ?></center></td>
					<td><center><?php echo $cuenta["accounts"]["name"]; ?></center></td>
							
					<td><center><a href="<?php echo APP_URL. "cuentas/editar/". $cuenta["accounts"]["id"]; ?>" class="btn btn-primary mr-3">Editar</a><a href="<?php echo APP_URL. "cuentas/eliminar/". $cuenta["accounts"]["id"]; ?>" class="btn btn-danger mr-3">Eliminar</a>
					</center>
					</td>
				</tr>
				<?php endforeach; ?>
			</table>
		</div>
	</div>
</div>





