<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="display-4 text-center">Lista de Categorias</h2>
            
			<a href="<?php echo APP_URL. "categorias/agregar"; ?>" class="btn btn-outline-success mb-3">Agregar Categoria</a>
        	<a href="<?php echo APP_URL. "cuentas/index"; ?>" class="btn btn-outline-primary mb-3">Regresar</a>
		
        	<table border="1" class="table table-striped table-dark table-responsive-lg">
				<tr>
					<th><center>ID</center></th>
					<th><center>Nombre</center></th>
					<th><center>Acción</center></th>
				</tr>
				<?php foreach ($this->categorias as $categorias): ?>
				<tr>
					<td><center><?php echo $categorias["categories"]["id"]; ?></center></td>
					<td><center><?php echo $categorias["categories"]["name"]; ?></center></td>
					<td><center><a href="<?php echo APP_URL. "categorias/editar/". $categorias["categories"]["id"]; ?>" class="btn btn-primary mr-3">Editar</a><a href="<?php echo APP_URL. "categorias/eliminar/". $categorias["categories"]["id"]; ?>" class="btn btn-danger mr-3">Eliminar</a></center>
					</td>
				</tr>
				<?php endforeach; ?>
			</table>
		</div>
	</div>
</div>